'use client'

import {Providers} from "@/app/providers";
import styled from "@emotion/styled";

export const GlobalAppStyle = styled.div`
  margin: 0 85px;
`

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="eng">
          <body>
              <Providers>
                  {children}
              </Providers>
          </body>
      </html>
  )
}
